#!/bin/sh

services_to_restart=""
for cgroup in /sys/fs/cgroup/unified/system.slice/*.service
do
    while IFS= read -r pid
    do
        if grep -q '(deleted)$' /proc/"$pid"/smaps
        then
            services_to_restart="$services_to_restart$(basename "$cgroup") "
            break
        fi
    done < "$cgroup"/cgroup.procs
done

if [ -n "$services_to_restart" ]
then
    set -x
    echo $services_to_restart
fi


